"""Leakage-safe Stage 5 router components."""

from .feature_provider import (
    CheckpointHashError,
    CheckpointNotFoundError,
    DINOV2_S14_ARCHITECTURE,
    FeatureProvider,
    FrozenVisualBackboneProvider,
    RouterBackboneConfig,
    RouterBackboneConfigError,
    RouterBackboneError,
    VisualBackboneConfig,
    checkpoint_sha256,
    freeze_visual_backbone,
    load_router_backbone_config,
    verify_local_checkpoint,
    visual_backbone_is_frozen,
)
from .feature_cache import (
    CachedImageFeatures,
    EncodedFeatureBatch,
    FeatureCache,
    FeatureCacheError,
    FeatureCacheIntegrityError,
    FeatureEncodingError,
    encoder_fingerprint,
    file_sha256,
)
from .normal_domain import (
    NormalDomainError,
    NormalDomainInputError,
    NormalDomainSignature,
    NormalDomainSignatureEncoder,
    NormalDomainStatistics,
    build_normal_signatures,
    compute_normal_domain_statistics,
    write_normal_signatures_parquet,
)

__all__ = [
    "CheckpointHashError",
    "CheckpointNotFoundError",
    "DINOV2_S14_ARCHITECTURE",
    "FeatureProvider",
    "FrozenVisualBackboneProvider",
    "RouterBackboneConfig",
    "RouterBackboneConfigError",
    "RouterBackboneError",
    "VisualBackboneConfig",
    "checkpoint_sha256",
    "freeze_visual_backbone",
    "load_router_backbone_config",
    "verify_local_checkpoint",
    "visual_backbone_is_frozen",
    "CachedImageFeatures",
    "EncodedFeatureBatch",
    "FeatureCache",
    "FeatureCacheError",
    "FeatureCacheIntegrityError",
    "FeatureEncodingError",
    "encoder_fingerprint",
    "file_sha256",
    "NormalDomainError",
    "NormalDomainInputError",
    "NormalDomainSignature",
    "NormalDomainSignatureEncoder",
    "NormalDomainStatistics",
    "build_normal_signatures",
    "compute_normal_domain_statistics",
    "write_normal_signatures_parquet",
]
